---
kind: Deployment
apiVersion: apps/v1
metadata: 
  name: mydeployment
spec: 
  replicas: 3
  strategy:
    type: Recreate
  selector: 
    matchLabels:  # Corrected from 'matchlabel'
      app: myapp
  template:
    metadata:
      labels:  # Added this line
        app: myapp  # Corrected this line and moved under 'labels'
    spec:
      containers:
      - image: swakam/myimage
        name: mycontainer
        ports:
        - containerPort: 8501  # Corrected 'continerPort' to 'containerPort'
---
kind: Service
apiVersion: v1
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 8501
    nodePort: 30001
